name: Java CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Give execute permission
        run: chmod +x install-libs.sh

      - name: Install dependencies
        run: |
          # Ejecutar el script para instalar las librerías
          ./install-libs.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy application.properties.dist to application.properties
        run: cp application.properties.dist application.properties

      - name: Update encryption.secret-key in application.properties
        run: sed -i 's/^encryption.secret-key=.*/encryption.secret-key=${{ secrets.ENCRYPTION_SECRET_KEY }}/' application.properties

      - name: Build the Java project
        run: mvn clean package

      - name: Build multi-platform Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ms-firma-digital-samoyed:latest
          platforms: linux/amd64,linux/arm64

      - name: Cleanup
        run: |
          docker buildx prune --all --force
